title: Cesar's Ramirez CIT_480 Blog 8

logo: /assets/img/AWS-EC2.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
